[project]
name = "test-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KonstantinVas", email = "110903969+KonstantinVas@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
test-python = "test_python:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.hatch.build.targets.wheel]
packages = ["hexlet_pytest"]